# Generated by Django 2.1.2 on 2018-12-12 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20181212_1322'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserLikes',
            new_name='UserLike',
        ),
    ]
