# Generated by Django 2.1.2 on 2018-12-12 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20181212_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlike',
            name='liked',
        ),
        migrations.RemoveField(
            model_name='userlike',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='likes',
            field=models.ManyToManyField(null=True, to='login.User'),
        ),
        migrations.DeleteModel(
            name='UserLike',
        ),
    ]
