# Generated by Django 2.1.2 on 2018-12-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20181212_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='likes',
            field=models.ManyToManyField(null=True, related_name='_user_likes_+', to='login.User'),
        ),
    ]
