# Generated by Django 2.1.2 on 2018-12-12 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20181212_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='likes',
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userLiking', to='login.User'),
        ),
        migrations.AddField(
            model_name='like',
            name='userLiked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userLikedBy', to='login.User'),
        ),
    ]
